repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^corpus/tib_run_a/objects/
      - id: trailing-whitespace
        exclude: ^corpus/tib_run_a/objects/
